import type { NextPage } from "next";
import Head from "next/head";
import Layout from "@components/Layout";
import Intro from "@components/Intro";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Goal app</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<Intro></Intro>
			</Layout>
		</div>
	);
};

export default Home;
